//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTodo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class subtasks
    {
        public int SubTaskId { get; set; }
        public string SubTaskName { get; set; }
        public int TodoId { get; set; }
    }
}
